state_filename: "trans_e.ckpt-11288"
model: TransD
dataset_filename: test_triplets.tfrecord
triplet_list_filename: training_triplets.list
entity_map_filename: entity_id.map
relation_map_filename: relation_id.map
options:
  batch_size: 50
  embedding_size:
    entity: 14505
    relation: 237
    hidden: 50
