model_options:
  general: &general
    embedding_size:
      entity: 100000
      relation: 100000
      hidden: 50
    train_iterations: 1000
    margin: 1.0
    alpha: 0.001
    lambda: 0.000
  transE: &transE
    <<: *general

name: "simple_transe"
flow:
  - model: TransE
    log_level: VERBOSE
    state_filename: "trans_e.ckpt"
    dataset_filename: "train_triplets.tfrecord"
    log_device_placement: True
    num_gpus: 0
    optimizer: SGD
    options:
      <<: *transE

